on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: setup-nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
